config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    # アクションの追加
    member do
      get 'fav'
    end
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  # クエリのデフォルトソートを降順にする
  default_scope -> { order(created_at: :desc) }
  # 1対多
  has_many :comments

  # バリデーション 3文字以上
  validates :title, presence: true, length: { minimum: 3 }
  validates :text, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    # モデルオブジェクトから全件取り出して変数に格納
    @posts = Post.all
  end

  def new
    # モデルオブジェクトを生成
    @post = Post.new
  end

  def create
    # モデルオブジェクトの生成と保存(引数は属性)
    @post = Post.new(post_params)

    if @post.save # モデルの保存に成功したかどうかを真偽値で返す
      redirect_to @post # 保存した@postの[show]にリダイレクトされる
    else
      #render
      # 指定したテンプレートを返す
      # 対応しているテンプレートを呼ぶ際は、このメソッドを呼ぶ必要はない
      # [http://railsdoc.com/controller#レンダリング(render)]

      # status(HTTPステータス) -> バリデーションエラー(unprocessable_entity)としてnewをレンダリング
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # find : データベースからデータを検索する
    @post = Post.find(params[:id])
  end

  def fav
    # params[:page]が存在しない場合の処理はindexアクションを実行
    if params[:page].nil?
      redirect_to :action => :index
    else # elseなくても動作する？
      # DBからparams[:id]をキーにして取得したモデルのfavをincrement
      Post.find(params[:id]).increment!(:fav)
      redirect_to :action => :show
    end

  end

  private
  def post_params
    # params が :post というキーを持ち、
    # params[:post] は :title, :text というキーを持つハッシュ(連想配列)であること を検証する
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<li>
  <p class="comment"><%= comment.body %></p>
  <dl class="commenter">
    <dt>投稿者：</dt>
    <dd><%= comment.commenter %></dd>
  </dl>
  <time><%= comment.created_at.to_s %></time>
</li>

app/views/comments/_form.html.erb
<div class="comment-form-area">
  <%= form_for([@post, @post.comments.build]) do |f| %>
      <div class="commenter-area">
        <%= f.label :commenter, '投稿者' %>
        <%= f.text_field :commenter, class: 'commenter' %>
      </div>

      <div>
        <%= f.text_area :body, cols: 60, rows: 3, class: 'comment-text', placeholder: 'コメントを入力してください' %>
      </div>

      <div class="btn-area">
        <%= f.submit '投稿' %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>さわやか3組</title>
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content=IE=edge">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div id="wrap">
  <header class="main-header">
    <div class="title">
      <h1><a href="/">さわやか3組</a></h1>
      <h2>いってみよう やってみよう</h2>
    </div>
    <nav class="h-nav">
      <ul>
        <li><%= link_to 'TOP',posts_path %></li>
        <li><%= link_to 'NEW POST',new_post_path %></li>
        <li><%= link_to 'GitHub', 'https://github.com/yirr/rails-blog' %></li>
      </ul>
    </nav>
  </header>

  <%= yield %>
</div>
</body>
</html>

app/views/posts/index.html.erb
<main class="posts">
  <% @posts.each do |post| %>
      <article>
        <header>
          <h3 class="a-title"><%= link_to post.title, post %></h3>
          <%= link_to '記事を読む→', post , class: 'more-link'  %>
        </header>
        <div class="a-bot">
          <ul>
            <li class="fav-area">
              <%=	link_to 'いいね', fav_post_path(post), class: 'fav-btn' %>
              <span class="fav-num"><%= post.fav %></span>
            </li>
            <li>コメント(<%= post.comments.count %>)</li>
            <li>
              <time>投稿日時:<%= post.created_at.to_s(:published_on) %></time>
            </li>
          </ul>
        </div>
      </article>
  <% end %>
</main>

<footer>

</footer>

app/views/posts/new.html.erb
<main class="new-post">
  <div class="card">
    <h3>新しい記事</h3>
    <%= form_for :post, url: posts_path do |f| %>
        <% if @post.errors.any? %>
            <div id="error">
              <h2>入力エラー</h2>
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div class="title">
          <%= f.label :title, 'タイトル' %>
          <%= f.text_field :title %>
        </div>

        <div class="naiyou">
          <%= f.label :text, '内容' %>
          <%= f.text_area :text, rows: 8 %>
        </div>

        <div class="btn-area">
          <%= f.submit class: 'common-submit-btn' %>
        </div>
    <% end %>
  </div>
</main>

app/views/posts/show.html.erb
<main class="show-a">
  <article class="show-article">
    <header>
      <h3 class="a-title"><%= @post.title %></h3>
    </header>
    <p class="a-text">
      <%= @post.text %>
    </p>
    <div class="a-bot">
      <ul>
        <li class="fav-area">
          <%= link_to 'いいね', fav_post_path(@post, :page => @post), class: 'fav-btn' %>
          <span class="fav-num"><%= @post.fav %></span>
        </li>
        <li>コメント(<%= @post.comments.count %>)</li>
        <li>
          <time><%= @post.created_at.to_s %></time>
        </li>
      </ul>
    </div>
  </article>

  <!-- コメント表示部 -->
  <div class="comment-area">
    <div class="comment-disp-area">
      <h3>コメント</h3>
      <% if @post.comments.count == 0 %>
          <p class="no-comment">コメントはありません</p>
      <% else %>
          <ul class="comment-list">
            <%= render @post.comments %>
          </ul>
      <% end %>
    </div>
    <!-- コメント記入欄 -->
    <h3>コメントを残す</h3>
    <%= render 'comments/form' %>
  </div>
</main>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to 'blog', controller: 'posts' %>